name: setup

on:
  push:
    branches: 
      - '*'
  pull_request:
    types: [opened, edited, reopened]
  merge_group:
    branches:
      - '*'

jobs:
  dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache node modules

        run: npm ci

      - name: upload dependencies
        uses: actions/upload-artifact@v4
        with:
          name: dependencies
          path: node_modules
          retention-days: 15
    
      
    