name: setup

on:
  push:
    branches: 
      - '*'
  pull_request:
    types: [opened, edited, reopened]
  merge_group:
    branches:
      - '*'

jobs:
  dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

    
      
    