name: tests

on:
  workflow_run:
    workflows:
      - setup
    types:
      - completed
  push:
jobs:
  syntax:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: eslint
        run: npm run lint
  build:
    needs: syntax
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: npm run build

    
    
      
    