name: tests

on:
  push:
    branches: 
      - '*'
  pull_request:
    types: [opened, edited, reopened]
    branches: 
      - '*'
  merge_group:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
       test: [lint, build]
    steps:
      - uses: actions/checkout@v4
      - name: ci
        run: npm ci
      - name: ${{ matrix.test }}
        run: npm run ${{ matrix.test }}


    
      
    