name: overflow

on:
  workflow_run:
    workflows: ["setup"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up environment
        run: echo "Setting up environment..."

      - name: Run overflow process
        run: echo "Running overflow process..."
